#include "memory_scheduler_stress.h"
#include <iostream>

void MemorySchedulerStress::generate_stress() {

    std::cout << "\n";
    std::cout << "========================================\n";
    std::cout << " PHASE 14 MEMORY SCHEDULER STRESS TEST\n";
    std::cout << "========================================\n";
    std::cout << "Injecting 20 WRITEs + 4 READs at "
              << sc_time_stamp() << "\n";
    std::cout << "Expected write-drain entry threshold: 13\n";
    std::cout << "Expected write-drain exit threshold: 8\n";
    std::cout << "========================================\n";

    // ------------------------------------------------------------
    // Inject all transactions in the same simulation delta.
    //
    // First 20 transactions are WRITEs.
    // Last 4 transactions are READs.
    //
    // This intentionally creates:
    //
    //     write_queue = 20
    //     read_queue  = 4
    //
    // before the memory-controller scheduler gets a chance to
    // service the queues.
    // ------------------------------------------------------------

    for (unsigned int i = 0; i < 24; ++i) {

        tlm::tlm_generic_payload& trans = transactions[i];

        trans.set_data_ptr(&data[i * 256]);
        trans.set_data_length(256);
        trans.set_streaming_width(256);
        trans.set_byte_enable_ptr(nullptr);
        trans.set_byte_enable_length(0);
        trans.set_dmi_allowed(false);
        trans.set_response_status(tlm::TLM_INCOMPLETE_RESPONSE);

        // Keep addresses within the existing address-mapping range.
        trans.set_address(0x10000 + static_cast<uint64_t>(i) * 0x100);

        if (i < 20) {
            trans.set_command(tlm::TLM_WRITE_COMMAND);
        } else {
            trans.set_command(tlm::TLM_READ_COMMAND);
        }

        AXIExtension* ext = new AXIExtension;
        ext->master_id = 99;
        ext->qos = 1;
        ext->parent_id = 1000;
        ext->child_id = i;

        trans.set_extension(ext);

        tlm::tlm_phase phase = tlm::BEGIN_REQ;
        sc_time delay = SC_ZERO_TIME;

        socket->nb_transport_fw(trans, phase, delay);
    }

    std::cout << "[STRESS] All 24 requests injected at "
              << sc_time_stamp() << "\n";

    // No more traffic is generated by this test process.
}

tlm::tlm_sync_enum MemorySchedulerStress::nb_transport_bw(
    tlm::tlm_generic_payload& trans,
    tlm::tlm_phase& phase,
    sc_time& delay) {

    if (phase == tlm::BEGIN_RESP) {
        return tlm::TLM_COMPLETED;
    }

    return tlm::TLM_ACCEPTED;
}
